# Generated by Django 4.0.2 on 2022-03-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
