# Generated by Django 4.0.2 on 2022-03-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='name_low',
            field=models.CharField(default='<django.db.models.fields.charfield>', max_length=100),
        ),
    ]
