# Generated by Django 4.0.2 on 2022-03-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='Услуга', max_length=64),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.IntegerField(default=15),
        ),
    ]
