# Generated by Django 4.0.2 on 2022-03-11 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('staff', '0002_alter_employee_organization_alter_employee_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organization.organization'),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
