# Generated by Django 4.0.2 on 2022-03-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_admin_organization_alter_employee_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='confirmed',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='employee',
            name='confirmed',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
