# Generated by Django 4.0.2 on 2022-03-14 11:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_workday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 11, 6, 55, 580923, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workday',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 11, 6, 55, 580923, tzinfo=utc)),
        ),
    ]
