# Generated by Django 4.0.2 on 2022-03-14 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_workday_date_alter_workday_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 14)),
        ),
        migrations.AlterField(
            model_name='workday',
            name='end',
            field=models.TimeField(default=datetime.time(18, 20, 13, 826478)),
        ),
        migrations.AlterField(
            model_name='workday',
            name='start',
            field=models.TimeField(default=datetime.time(18, 20, 13, 826478)),
        ),
    ]
