# Generated by Django 4.0.2 on 2022-03-14 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_alter_workday_end_alter_workday_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='end',
            field=models.TimeField(default=datetime.time(23, 20, 12, 645552)),
        ),
        migrations.AlterField(
            model_name='workday',
            name='start',
            field=models.TimeField(default=datetime.time(23, 20, 12, 645552)),
        ),
    ]
