# Generated by Django 4.0.2 on 2022-03-13 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_user_username_user_name_user_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
